version: '3'

services:
  app:
    build: ./app
    environment:
      - VITE_API_URL=http://api:8080
    ports:
      - '3000:3000'
    depends_on:
      - api

  api:
    build: ./api
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
